// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('banuba (user2)', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('banuba (user2)', async function () {
    await driver.get("https://school.ip.tv/deeplink?api=mas&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjdkZjBiYTk4ODE3MGVjMjYxYjRiYiIsInJlYWxtIjoic2Nob29sIiwiaWF0IjoxNjc3MTg4ODc1fQ.S9IzOuZeLgJp6ja0qOUPD0IlEX5XIj-8qOO-NCML_vg")
    await driver.manage().window().setRect({ width: 1294, height: 915 })
    await driver.findElement(By.css(".css-1irvnn5")).click()
    await driver.findElement(By.id("db_invite_name")).click()
    await driver.findElement(By.id("db_invite_name")).sendKeys("test")
    await driver.findElement(By.id("db_inv_button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.id("banuba_effect")).click()
    {
      const dropdown = await driver.findElement(By.id("banuba_effect"))
      await dropdown.findElement(By.xpath("//option[. = 'Background_doc']")).click()
    }
    await driver.findElement(By.id("dbdev_confirm")).click()
    })
})
